name: ci

on: [push, pull_request]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby: [2.5, 2.6, 2.7, '3.0', '3.1', head, jruby, jruby-head]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: true
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake
